<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <RootNamespace>App.Browser</RootNamespace>

        <PublishTrimmed>false</PublishTrimmed>
        <PublishAot>false</PublishAot>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\JabChat\JabChat.csproj" />
    </ItemGroup>
</Project>
