<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <RootNamespace>App.Browser</RootNamespace>

        <PublishTrimmed>false</PublishTrimmed>
        <PublishAot>false</PublishAot>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\JabChat\JabChat.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\sqlite-wasm-3530300\jswasm\sqlite3-opfs-async-proxy.js" />
      <_ContentIncludedByDefault Remove="wwwroot\sqlite-wasm-3530300\jswasm\sqlite3-worker1-bundler-friendly.mjs" />
      <_ContentIncludedByDefault Remove="wwwroot\sqlite-wasm-3530300\jswasm\sqlite3-worker1-promiser-bundler-friendly.mjs" />
      <_ContentIncludedByDefault Remove="wwwroot\sqlite-wasm-3530300\jswasm\sqlite3-worker1-promiser.js" />
      <_ContentIncludedByDefault Remove="wwwroot\sqlite-wasm-3530300\jswasm\sqlite3-worker1-promiser.mjs" />
      <_ContentIncludedByDefault Remove="wwwroot\sqlite-wasm-3530300\jswasm\sqlite3-worker1.js" />
      <_ContentIncludedByDefault Remove="wwwroot\sqlite-wasm-3530300\jswasm\sqlite3-worker1.mjs" />
      <_ContentIncludedByDefault Remove="wwwroot\sqlite-wasm-3530300\jswasm\sqlite3.js" />
      <_ContentIncludedByDefault Remove="wwwroot\sqlite-wasm-3530300\jswasm\sqlite3.mjs" />
      <_ContentIncludedByDefault Remove="wwwroot\sqlite-wasm-3530300\jswasm\sqlite3.wasm" />
    </ItemGroup>
</Project>
