//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MainView_Greeting {
            get {
                return ResourceManager.GetString("MainView.Greeting", resourceCulture);
            }
        }
        
        public static string IntroPage_Carousel_Messenger {
            get {
                return ResourceManager.GetString("IntroPage.Carousel.Messenger", resourceCulture);
            }
        }
        
        public static string IntroPage_Carousel_Status {
            get {
                return ResourceManager.GetString("IntroPage.Carousel.Status", resourceCulture);
            }
        }
        
        public static string IntroPage_Carousel_CrossPlatform {
            get {
                return ResourceManager.GetString("IntroPage.Carousel.CrossPlatform", resourceCulture);
            }
        }
        
        public static string IntroPage_Welcome {
            get {
                return ResourceManager.GetString("IntroPage.Welcome", resourceCulture);
            }
        }
        
        public static string IntroPage_Carousel_ButtonConnect {
            get {
                return ResourceManager.GetString("IntroPage.Carousel.ButtonConnect", resourceCulture);
            }
        }
        
        public static string IntroPage_Carousel_ButtonLater {
            get {
                return ResourceManager.GetString("IntroPage.Carousel.ButtonLater", resourceCulture);
            }
        }
        
        public static string IntroPage_CallToAction {
            get {
                return ResourceManager.GetString("IntroPage.CallToAction", resourceCulture);
            }
        }
    }
}
